### ISSUE TITLE
NoMethodError: private method `save_impl' called for..

### ISSUE THREAD

**Issue by nthx** [jruby/image_voodoo#20]
Hi!

In the project I'm using ImageVoodoo gem indirectly. It's a depedency of another gem: `carrierwave_imagevoodoo (0.1.0-java)`

We've recently upgraded imagevoodoo from `0.8.2` to` 0.8.6` and this error started appearing:

    NoMethodError (private method `save_impl' called for #<ImageVoodoo:0x54440629>):#012  app/services/foobar.rb:50

We don't use your gem directly (nor carrierwave).

Looks like one of 2 things happened and I'm not sure which one:
* you've modified public API in a patch release and that would be bad
* carrierwave (probably) is invoking a private method from your codebase - and the effect is bad as you may see

Please, do an analysis and/or fix if that's possible.

**Comment by enebo** [comment]
@nthx could you provide a full or partial backtrace?  I can read the code to try and understand what is wrong but I suspect a backtrace would make the problem obvious.

**Comment by enebo** [comment]
Actually this was trivial to track down but I am a bit confused now...

https://github.com/tazsingh/carrierwave_imagevoodoo/blob/master/lib/carrierwave_imagevoodoo.rb#L154

So carrierwave_imagevoodoo calls save_impl which is currently private but I always thought this was private.  Even the name implies it is private.  I don't remember actually changing this but I will make it public again so that gem still works.  It has to be me otherwise I don't see how this would have ever worked?

**Comment by enebo** [comment]
0.8.9 has been pushed.  This version also have a lot of what should be zero-sum changes due to rubocop.  I was also not able to actually get carrierwave_imagevoodoo to load properly (it seems like it has not been updated in a long long time) so you will need to let me know if fixing this uncovers anything else broken.

**Comment by nthx** [comment]
I will do the test with the latest release and let you know if it's fixed.
Due to the way it's setup I don't have better stack :-(

**Comment by nthx** [comment]
The function is clearly public in your 0.8.2.
It went private in 0.8.6 (or before) 

    gems/jruby-1.7.24/gems/image_voodoo-0.8.2/lib/image_voodoo/awt.rb
    LINE_99: def save_impl(format, file)
    LINE_178: private

:-D

**Comment by enebo** [comment]
@nthx yeah I clearly must have moved it between those two.  I am not sure with the age of this gem I can hide behind the argument that it is not 1.0 yet either :)
